- policy/signals.py
TICKET: https://openimis.atlassian.net/browse/OE0-74
Here in that module will be declaration of Signal. But this Signal will be connected in 'Contract' module https://github.com/openimis/openimis-be-contract_py/pull/50
> OE0-74: added signal for check type of policy: informal or formal sector

- policy/models.py
- policy/services.py
- policy/test_values.py
- policy/values.py
Comes right after : https://github.com/openimis/openimis-be-product_py/pull/9
> chore(Products): Adapt for the product migration

- policy/signals.py
TICKET: https://openimis.atlassian.net/browse/OPL-42
> OPL-42: signal for creating Invoice after creating policy

- policy/test_services.py
part of TICKET: https://openimis.atlassian.net/browse/OP-758
fixed one broken test due to issue on 'db.cursor' mock
> OP-758: fixed test due to using in bad way 'cursor' mock

- policy/services.py
> Django 3.1

- policy/test_services.py
[https://openimis.atlassian.net/browse/OP-868](https://openimis.atlassian.net/browse/OP-868)
Changes:
- Changed handling of JSON fields from JSON strings to python dictionaties (Django 3.2 update)
- Fixed TestCase handling (added all missing calls to super.setUpClass, super.setUp, removed unecessary teardowns)
- Removed some unused code/comments/imports
- Fixed code formatting
> OP-868 Fix CI issues caused by Django 3.2 update

- policy/services.py
https://openimis.atlassian.net/browse/OP-938
Bug identified by @tdethier
> frontend and GQL type use uuid instead of policyUuid

- policy/schema.py
Ticket:
https://openimis.atlassian.net/browse/OP-1040
Changes:
- resolver is extended with location filters
- query set is extended with new location filtering
Related PR:
https://github.com/openimis/openimis-fe-policy_js/pull/24
> Feature/op 1040: filter officers' list by selected location in the policy form

- policy/test_helpers.py
Added test helper function for fixing `generateinsurees` Django command
> Fixing generateinsurees Django command

- policy/schema.py
https://openimis.atlassian.net/browse/OTC-882
> OTC-882: Policy value is not fetched correctly 

- policy/values.py
Ticket: https://openimis.atlassian.net/browse/OTC-901
Changes:
- Policy value in query is explicitly converted to decimal.
> OTC-901: Conversion of policy value to decimal.

- policy/gql_queries.py
- policy/schema.py
https://openimis.atlassian.net/browse/OTC-878
> OTC-878: add permission to gql mutations and queries

- .github/workflows/openmis-module-test.yml
- policy/services.py
- policy/test_services.py
https://openimis.atlassian.net/browse/OTC-780
Now it is calculated by summing all the chosen items or services from all claims assigned to insuree.
It is a part of frontend PR: https://github.com/openimis/openimis-fe-policy_js/pull/28
> OTC-780: fix calculation of used service or item

- policy/services.py
https://openimis.atlassian.net/browse/OP-1346
This PR takes into consideration extra members ceiling when calculating ceiling for policy.
> OP-1346: calculate ceiling taking into account extra members

- policy/models.py
- policy/services.py
Ticket:
https://openimis.atlassian.net/browse/OTC-1005
Changes:
- balance value for premiums is now only calculating active contributions
> OTC-1005: fixed calculating balance for deleted premiums

- policy/services.py
https://openimis.atlassian.net/browse/OTC-780
This PR will fix calculating item or services that were never used in claim.
> OTC-780: when item or serviece never used dont count it

- policy/services.py
https://openimis.atlassian.net/browse/OTC-1022
This PR adds services validity check that was missing.
> OTC-1022: fix filtering of items in check eligibility

- policy/utils.py
https://openimis.atlassian.net/browse/OP-1559
This PR changes filtering of get_queryset_at_date to be filter against date.
> OP-1559: filter using only date

- policy/services.py
> hotfix: if value None change it to 0

- policy/schema.py
Ticket: https://openimis.atlassian.net/browse/ONI-39
FE: https://github.com/openimis/openimis-fe-policy_js/compare/feature/ONI-39?expand=1
Changes:
- Added filter for confirmation type of family connected to policy.
> ONI-39: Filtering policies by confirmation type of family.

- policy/schema.py
- policy/values.py
https://openimis.atlassian.net/browse/OP-1644
Backdated products were included
> OP-1644: Product: Cycles and Discounts are not working

- policy/schema.py
- policy/values.py
MERGING RELEASE branches
Release release/23.10
> MERGING develop into release/23.10

- policy/gql_mutations.py
- policy/services.py
Ticket: https://openimis.atlassian.net/browse/OP-1823
FE: https://github.com/openimis/openimis-fe-policy_js/pull/85
Changes:
- Added code for handling payer data while creating contribution
> OP-1823: Add option to select a payer in a single payment.

- policy/schema.py
- policy/services.py
- policy/tests_gql.py
MERGING develop into release/24.04
> MERGING develop into release/24.04
